### PR TITLE
Fixes for import asset package

### PR DESCRIPTION
**Pull request by caseyyee**
Tried build with included sample scene on both PC and Mac.
Tested with and without VR in-editor on PC.
Also tested with new Unity project import asset package on both PC and Mac.

### CODE REVIEW

**Comment by cvan** [comment]
this seems to break the demo scene:

screenshot 215
screenshot 214

I assume you were trying to just fix the scripts. let me know if I'm doing something wrong! thanks :+1:

**Comment by cvan** [comment]
@caseyyee: I see this logged error in the console, btw: `SendMessage: object WebVRCameraSet not found!`

screenshot 216

**Comment by cvan** [comment]
@caseyyee it works!! weird, I thought I had done that. your instructions worked.

(btw, I've been dev/testing entirely on Windows now, no longer macOS for everyday work now - all in hopes of trying to better test the VR support/flows)

**Comment by caseyyee** [comment]
Thanks!
Yeah, my guess is that anyone working on this stuff will probably be on PC.  Can we find out from the telemetry data?

**Pull request merged**
