### PR TITLE
adds polyfill sourcemap

### LINKED ISSUE #54: fix `Source map error` JS error for missing external source-maps file in `webvr-polyfill`
https://github.com/caseyyee/unity-webvr-export/blob/e119886/Assets/WebVR/Plugins/webvr-polyfill.min.jspre#L43

screen shot 2017-12-19 at 1 10 19 pm

### PR DESCRIPTION
**Pull request by caseyyee**
Fix #54 
also moves this into the main templates folder.

just to be consistent with all the other library usage.

probably time to add a js folder

As a note, Polyfill ver:
https://github.com/immersive-web/webvr-polyfill/releases/tag/v0.9.36

### CODE REVIEW

**Comment by caseyyee** [comment]
ok took materials.meta out.

**Comment by delapuente** [comment]
I think that's out of reach. The Unity player exhausts device memory. This is also happening in Chrome and Firefox from time to time.

**Comment by delapuente** [comment]
Well, not out of reach but it requires optimizing the Unity loader and probably do more than JS to fix it.

**Comment by cvan** [comment]
you can manually bump the memory size from the Unity WebGL Player Settings or the emscripten module loader options in `index.html`

**Comment by delapuente** [comment]
Should we add it to the FAQ #118 , perhaps?

**Comment by delapuente** [comment]
Oh, I see them there!

**Comment by delapuente** [comment]
This is duplicating #54 according to the current wording. I'm going to close that and test and merge this.

For the posterity:

1. We'll add an out-of-memory-related entry in the FAQ
2. We are tracking how to update the polyfill in #113 

If you see the error regarding [`requestAnimationFrame` and described here](https://github.com/mozilla/unity-webvr-export/issues/54#issuecomment-363622646), open another issue.

**Comment by delapuente** [comment]
Fix #54

**Pull request merged**
