### PR TITLE
create thumbnail for WebVR Player (fixes issue #112)

### LINKED ISSUE #112: Improve the icon for the "WebVR" Player in `Player Settings`
1. Open the Unity project
2. Open the `Player Settings` from `Edit > Project Settings > Player`
3. Click the HTML5 icon to expand the `WebGL Settings` tab
4. Under `WebGL Template`, notice the `WebVR` image which contains a scrunched-up HTML5 icon.

We should create a fancier icon. That's all. Very minor.

### PR DESCRIPTION
**Pull request by cvan**
Fix #112

## before
screen shot 2018-02-26 at 11 19 16 pm

## after
screen shot 2018-02-26 at 11 18 32 pm

<hr>

## up close and personal
image

### CODE REVIEW

**Comment by delapuente** [comment]
I like it, @caseyyee do you have some aesthetic suggestion?

**Comment by cvan** [comment]
it is a little odd that the VR button is that visible when in VR mode (but that's what #130 will fix). but I think for now, most people won't notice or be bothered by that.

@caseyyee any issues with my merging this? it's definitely an improvement over the current icon lol (none!)

**Comment by caseyyee** [comment]
@cvan go for it!  I will work on getting something a little more identifiable in there.

Thanks for doing this!

**Comment by caseyyee** [comment]
@cvan you can use one of these.
icon
large
small

**Comment by caseyyee** [comment]
image

256x256 as per slack w/ browser window

**Comment by cvan** [comment]
thanks, @caseyyee!

<hr>

for posterity's sake: see the source files for these icons produced by @caseyyee:

[webvr-asset-store-icons.zip](https://github.com/mozilla/unity-webvr-export/files/1765360/webvr-asset-store-icons.zip)

original icon sent via Slack (548×548)

thumbnail (256×256)

**Comment by cvan** [comment]
branch updated!

screen shot 2018-02-27 at 6 19 59 pm

thanks, @caseyyee - it looks great 👍

**Pull request merged**
