### PR TITLE
Calculating transform parameters instead of overriding worldToCameraMatrix

### LINKED ISSUE #158: Make `GameObjects` attached to the cameras update accordingly to cameras' transformations.
Current code position eyes overriding [`worldToCameraMatrix`](https://docs.unity3d.com/ScriptReference/Camera-worldToCameraMatrix.html) instead of modifying the `transform` component. The transform component is not automatically updated to match the `worldToCameraMatrix` value so any `GameObject` attached to a camera is not correctly positioned relative to that camera. This makes the creation of GUI objects difficult since the position and orientation of the GUI must be calculated manually, frame by frame.

### PR DESCRIPTION
**Pull request by delapuente**
Fix #158. In addition, it advances in some of the efforts in #154 . Now, like Unity, it overrides the values of the `transform` component, so it can not be changed manually and it can continue affecting its children. The main/central camera can be considered the _head_ of the player so things can be positioned relative to the player's head (useful for GUIs).

### CODE REVIEW

**Comment by caseyyee** [comment]
@delapuente I tried this out.  Looks good in headset.

Issue is that the hand controllers are offset.  Seems like it may be the same amount from the world-space origin?

**Comment by delapuente** [comment]
Thank you very much @caseyyee I open #162 to discuss about how to manage controllers.

**Comment by delapuente** [comment]
@cva  @caseyyee do you think we can merge this and improve towards v1.1?

**Comment by caseyyee** [comment]
@delapuente looks good, but the offset controller needs to be solved along with this.  I'll make a complimentary patch that we can land it together.  otherwise looks great!

**Pull request merged**
