### PR TITLE
use OBJ/MTL instead of Blender file for 🏜 Desert Terrain environment (fixes issue #178)

### LINKED ISSUE #178: scene does not appear after Unity splash screen when building Unity project on Windows
I think most (all?) of us have been building the project in Unity on macOS and pointing Firefox on our VR computers to a local/ngrok URL.

I upgraded Unity (to the latest, Unity `2017.3.1f1` Personal Edition) on one of my Windows machines, and I couldn't get a build that loads properly. Generating a build from Unity on macOS still seems to work though (ignoring the terrain issue, which I've filed for in #177).

<hr>

screenshots below:

image
image
image
image

and the scene gets stuck there!

<hr>

@caseyyee @delapuente: can y'all comment here with the platforms (macOS or Windows) versions and workflows you have been building, testing, and developing with? that might help us get to the bottom of the inconsistencies I'm seeing here. thanks!

### PR DESCRIPTION
**Pull request by cvan**
Fix #178 

- Use OBJ/MTL files generated from Blender model source file
- Point the Unity scene to use the new models, applying the "Red" material
- Blender is no longer required to be installed on the system
- Remove old temp files (`*.blend1`)

### CODE REVIEW

**Comment by cvan** [comment]
thanks, I'll update this tomorrow. (@caseyyee if you have a minute, you might be able to eyeball the changes needed.)

**Comment by cvan** [comment]
(without Blender installed) on `master`:

`master`

in this PR (#212):



<hr>

@caseyyee any obvious idea why the objects on the desk aren't showing up? I don't think I've changed anything to occlude them, but I could be wrong.

thanks in advance for taking a peek!

**Comment by delapuente** [comment]
I think they are falling through the table. :P

**Comment by cvan** [comment]
@caseyyee: I updated the files for the Desert Environment models (OBJ+MTL+Blender files) from the ones you sent me.

in both VR and non-VR, notice how dark the lighting/material now appears:

screenshot of dark lighting (on macOS)

screenshot of dark lighting (on macOS)

screenshot of dark lighting (on Windows)

screenshot of dark lighting (on Windows)

<hr>

I'm running Unity version `2017.3.1f1`; I know the project settings are set to `2017.3.0f3`, and I believe that's the version you're using too. I doubt there was any breaking change in a patch-version update, but just figured I'd mention it.

**Comment by cvan** [comment]
@caseyyee okay, per our Slack conversation, I just fixed this by unchecking the `Static` property, and the lighting looks proper again now.

**Comment by caseyyee** [comment]
@cvan looks good!  r+ thanks for this!

**Pull request merged**
