### PR TITLE
patch webvr-polyfill to include fix for rAF on mobile (fixes issue #127; relevant to issue #113)

### PR DESCRIPTION
**Pull request by cvan**
- See fix added in v1.0.6 of the `cardboard-vr-display` dependency: https://github.com/immersive-web/cardboard-vr-display/commit/6f6a0c1e8b28eb4a3c861aeab4f814e93207fb85
- This file will eventually be replaced when `webvr-polyfill` is properly upgraded: https://github.com/mozilla/unity-webvr-export/issues/113

### CODE REVIEW

**Comment by delapuente** [comment]
@caseyyee , I've never seen this error so I'm not the one who can properly check if it is solved. Can you take a look?

**Comment by cvan** [comment]
@caseyyee ping on this - can you review ASAP? thank you

**Comment by cvan** [comment]
@itsthisjustin also, if you have a moment and are able, if you want to copy this file into your built project, and see if it fixes your issue, that'd help a ton. thank you in advance for your help 👍

**Comment by itsthisjustin** [comment]
Will do! @cvan

**Pull request merged**
