### PR TITLE
Updating WebVR polyfill

### LINKED ISSUE #54: fix `Source map error` JS error for missing external source-maps file in `webvr-polyfill`
https://github.com/caseyyee/unity-webvr-export/blob/e119886/Assets/WebVR/Plugins/webvr-polyfill.min.jspre#L43

screen shot 2017-12-19 at 1 10 19 pm

### PR DESCRIPTION
**Pull request by delapuente**
Fix #54

### CODE REVIEW

**Comment by delapuente** [comment]
@caseyyee I need help testing with all devices since I just have the VIVE

See testing devices suggested by @cvan: https://github.com/mozilla/unity-webvr-export/issues/54#issuecomment-363233605

I've said in the bug there were errors in Android for Chrome and Firefox with both the old and new polyfills so what I would really do is to check if there are regressions. How?

1. Pass @cvan test suite to master right now and annotate the results per device
2. Apply the patch.
3. Pass @cvan test suite again and annotate the new results

Consider the test suite passed if there are no the same or less errors.

**Comment by caseyyee** [comment]
Tried it out.

Few issues:
1. Controllers don't work. (Oculus with FF)
2. User starts at Y-axis at 0 height.

**Comment by cvan** [comment]
@caseyyee: when you pulled this branch, did you generate a new Build? in this PR, the `Build/` files have not been updated. so that could explain it, if that is the case.

I looked at the source of https://raw.githubusercontent.com/delapuente/unity-webvr-export/2842060e69ff8d70a80c90c04b97a92e5408a1fe/Assets/WebVR/Plugins/webvr-polyfill.min.jspre, and it looks like the correct latest version of the `webvr-Polyfill`, and the external source-map comment at the end of the file is correctly removed.

let me know. I’ll test on my devices too.

**Comment by caseyyee** [comment]
Yup, I did do a new build.  The polyfill doesn't appear to be loading, so I moved it into the template where the other libraries are and instantiated it as per the docs.   

Still doesn't appear to be working -- still troubleshooting.

**Comment by caseyyee** [comment]
OK, So I looked into this further.  

It looks like there has been some functionality removed from the latest polyfill.   In previous versions, it returned a VR display on desktop and allowed for some basic mouse interactions.  With the new version, this been removed and is expected to be managed by the app dev now.

What I propose is if there is no major issue, leave the existing polyfill for the community release, and follow up with an update that implements the new polyfill while also having the responsive features for desktop.

**Comment by caseyyee** [comment]
So we decided that we won't block on this for now.  Will address as issue https://github.com/mozilla/unity-webvr-export/issues/54

**Pull request closed without merging**
